db: world
server:
  port: 8888
  servlet:
    context-path: /api/v1
    session:
      cookie:
        name: BIUSID
spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/${db}?characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
