db: test
server:
  port: 8888
  servlet:
    context-path: /api/v1
    session:
      cookie:
        name: BIUSID
spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/${db}?characterEncoding=UTF-8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: a-group
